#
# © Copyright IBM Corp. 2022, 2025
#

FROM icr.io/ibmz/python:3.13-bookworm
RUN apt-get update \
    && apt-get install -y \
        libopenblas-dev \
    && apt-get clean
RUN pip3 install numpy
ENTRYPOINT [ "python3" ]
CMD [ "--help" ]
